### ISSUE TITLE
Build issue in Ubuntu 12.10 Quantal

### ISSUE THREAD

**Issue by hotice** [Grive/grive#102]
Grive fails to build in Ubuntu 12.10 Quantal because of this:

[ 73%] Building CXX object libgrive/CMakeFiles/grive.dir/src/bfd/SymbolInfo.cc.o
In file included from /build/buildd/grive-0.2.0/libgrive/src/bfd/SymbolInfo.cc:25:0:
/usr/include/bfd.h:37:2: error: #error config.h must be included before this header
make[3]: **\* [libgrive/CMakeFiles/grive.dir/src/bfd/SymbolInfo.cc.o] Error 1

It builds just fine in Ubuntu 12.04 and older...
