### ISSUE TITLE
Build fails on Mac OS X

### ISSUE THREAD

**Issue by ptman** [Grive/grive#180]
git bisect tells me:

Linking CXX executable grive
Undefined symbols for architecture x86_64:
  "gr::Json::Json<long>(long const&)", referenced from:
      gr::State::Write(boost::filesystem::path const&) const in libgrive.a(State.cc.o)
  "gr::Json::Json<unsigned long>(unsigned long const&)", referenced from:
      gr::State::Write(boost::filesystem::path const&) const in libgrive.a(State.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [grive/grive] Error 1
make[1]: **\* [grive/CMakeFiles/grive_executable.dir/all] Error 2
make: **\* [all] Error 2
755ee1c9adfe290f68e18ddea0b01673186b3917 is the first bad commit
commit 755ee1c9adfe290f68e18ddea0b01673186b3917
Author: Nestal Wan me@nestal.net
Date:   Sun Apr 28 18:40:21 2013 +0800

```
new qt gui
```

**Comment by markmark1** [comment]
same issue how to get this to work In Mac or are there Mac binaries

**Comment by ptman** [comment]
I no longer have a mac to test
