### ISSUE TITLE
Can't build on Ubuntu 11.04 (‘VERSION’ was not declared in this scope)

### ISSUE THREAD

**Issue by edg2s** [Grive/grive#107]
/grive/src/main.cc: In function ‘int Main(int, char**)’:
 /grive/src/main.cc:136:26: error: expected primary-expression before ‘(’ token
 /grive/src/main.cc:136:44: error: expected ‘)’ before ‘VERSION’
 /grive/src/main.cc:144:27: error: ‘VERSION’ was not declared in this scope
